---
- name: create user and group
  become: yes
  shell: "groupadd -g 2000 sbfspot && useradd -d /home/sbfspot -u 2000 -g 2000 -m -s /bin/bash sbfspot"
  ignore_errors: yes

  tags:
   - run

- name: copy dockerfiles Base Image
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: pi
    mode: 0755
  with_items:
    - { src: 'build/Dockerfile', dest: '~/sbfspot-build/'}
  tags:
    - build

- name: build docker Base Image
  docker_image:
    path: ~/sbfspot-build
    name: sbfspot
    state: present
    debug: yes
  tags:
    - build

- name: copy Dockerfiles for spbfspot-collector
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: pi
    mode: 0755
  with_items:
    - { src: 'collector/Dockerfile', dest: '~/sbfspot-col-build/'}
    - { src: 'collector/SBFspot.sh', dest: '~/sbfspot-col-build/'}
  tags:
    - build

- name: build docker image spbfspot-col
  docker_image:
    path: ~/sbfspot-col-build
    name: sbfspot-col
    pull: no
    state: present
    debug: yes
  tags:
    - build

- name: copy Dockerfiles for spbfspot-uploader
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: pi
    mode: 0755
  with_items:
    - { src: 'uploader/Dockerfile', dest: '~/sbfspot-upl-build/'}
    - { src: 'uploader/SBFspotUploadDaemon.sh', dest: '~/sbfspot-upl-build/'}
  tags:
    - build

- name: build docker image spbfspot-upl
  docker_image:
    path: ~/sbfspot-upl-build
    name: sbfspot-upl
    pull: no
    state: present
    debug: yes
  tags:
    - build

- name: create folders
  become: yes
  file:
    path: '{{ item }}'
    owner: sbfspot
    group: sbfspot
    mode: 0775
    state: directory
  with_items:
    - /data/sbfspot
    - /data/sbfspot/logs
    - /data/sbfspot/config
  tags:
    - run

- name: copy sbfspot configfiles
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: pi
    group: sbfspot
    mode: 0775
  with_items:
    - { src: 'SBFspot.cfg', dest: '/data/sbfspot/config/'}
    - { src: 'SBFspot-1.cfg', dest: '/data/sbfspot/config/'}
    - { src: 'SBFspotUpload.cfg', dest: '/data/sbfspot/config/'}
  tags:
    - run

- name: remove container
  docker_container:
    name: '{{ item }}'
    state: absent
  with_items:
    - sbfspot-collector
    - sbfspot-collector-1
    - sbfspot-collector-month
    - sbfspot-collector-1-month
    - sbfspot-uploader
  ignore_errors: yes
  tags:
    - run

- name: run container sbfspot-collector
  shell: " docker run -v /etc/localtime:/etc/localtime:ro -v /data/sbfspot:/var/smadata -v {{ item.config }}:/opt/sbfspot/SBFspot.cfg --net=host --privileged --name {{ item.name }} sbfspot-col -v -ad1 -am0 -ae0"
  with_items:
    - { name: 'sbfspot-collector', config: '/data/sbfspot/config/SBFspot.cfg' }
    - { name: 'sbfspot-collector-1', config: '/data/sbfspot/config/SBFspot-1.cfg' }
  tags:
    - run
  ignore_errors: yes

- name: run container sbfspot-collector-month
  shell: " docker run -v /etc/localtime:/etc/localtime:ro -v /data/sbfspot:/var/smadata -v {{ item.config }}:/opt/sbfspot/SBFspot.cfg --net=host --privileged --name {{ item.name }}-month sbfspot-col -v -sp0 -ad0 -am1 -ae1 -finq"
  with_items:
    - { name: 'sbfspot-collector', config: '/data/sbfspot/config/SBFspot.cfg' }
    - { name: 'sbfspot-collector-1', config: '/data/sbfspot/config/SBFspot-1.cfg' }
  tags:
    - run
  ignore_errors: yes

- name: run container sbfspot-uploader
  shell: "docker run -dt --restart always -v /etc/localtime:/etc/localtime:ro -v /data/sbfspot:/var/smadata -v /data/sbfspot/config/SBFspotUpload.cfg:/opt/sbfspot/SBFspotUpload.cfg --name sbfspot-uploader sbfspot-upl"
  tags:
    - run


- name: adding crontab entry for sbfspot-collector
  become: true
  lineinfile:
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    path: /etc/crontab
# */5 5-23 * * * docker start -a sbfspot-collector > /dev/null 2>&1";
#*/5 5-23 * * * docker start -a sbfspot-collector-1 > /dev/null 2>&1
#55 05 * * * docker start -a sbfspot-collector-1-month > /dev/null 2>&1
#55 05 * * * docker start -a sbfspot-collector-month > /dev/null 2>&1

