   0.0  0.0   0:00.00 kthrotld
   56 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 iscsi_eh
   57 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 dwc_otg
   58 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 DWC Notificatio
   59 root       1 -19       0      0      0 S   0.0  0.0   0:00.00 vchiq-slot/0
   60 root       1 -19       0      0      0 S   0.0  0.0   0:00.00 vchiq-recy/0
   61 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 vchiq-sync/0
   62 root      20   0       0      0      0 S   0.0  0.0   0:00.00 vchiq-keep/0
   63 root      10 -10       0      0      0 S   0.0  0.0   0:00.00 SMIO
   65 root     -51   0       0      0      0 S   0.0  0.0   0:00.80 irq/92-mmc1
   68 root      20   0       0      0      0 S   0.0  0.0   0:04.17 mmcqd/0
   69 root      20   0       0      0      0 S   0.0  0.0   0:01.28 jbd2/mmcblk0p2-
   70 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 ext4-rsv-conver
   71 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 ipv6_addrconf
pi@raspberrypi:~/rpicam-docker $ sudo raspi
raspi-config  raspistill    raspivid      raspividyuv   raspiyuv
pi@raspberrypi:~/rpicam-docker $ sudo raspi-config
---
# tasks file for docker-rpi-cam

- name: copy dockerfiles to create container
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: pi
    mode: 0755
  with_items:
    - { src: 'Dockerfile', dest: '~/rpicam-docker/'}
    - { src: 'makefile', dest: '~/rpicam-docker/'}
    - { src: 'motion.conf', dest: '~/rpicam-docker/'}
    - { src: 'config.txt', dest: '~/rpicam-docker/'}
    - { src: 'docker-entry.sh', dest: '~/rpicam-docker/'}
    - { src: 'motion_event.sh', dest: '~/rpicam-docker/'}
    - { src: 'schedule.json', dest: '~/rpicam-docker/'}
    - { src: 'uconfig', dest: '~/rpicam-docker/'}

#- name: build docker image
#  make:
#    chdir: /home/pi/rpicam-docker
#    target: build

- name: build docker image
  docker_image:
    path: ~/rpicam-docker
    name: rpi-cam-web
    state: present 
    tag: rpi-cam-web
    debug: yes

- name: create nfs mount
  shell: docker volume create --driver local --opt type=nfs --opt o=addr=10.10.10.60,rw --opt device=:/Recordings nfscam
- name: Docker Run container
  shell: docker run -d --name=rpi-cam -p=80:80/tcp --mount source=nfscam,destination=/data --device=/dev/vchiq --device=/dev/vcsm rpi-cam-web --restart always
   chdir: ~/rpicam-docker
