---
# tasks file for docker-rpi-cam

- name: copy dockerfiles to create container
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: pi
    mode: 0755
  with_items:
    - { src: 'Dockerfile', dest: '~/rpicam-docker/'}
    - { src: 'makefile', dest: '~/rpicam-docker/'}
    - { src: 'motion.conf', dest: '~/rpicam-docker/'}
    - { src: 'config.txt', dest: '~/rpicam-docker/'}
    - { src: 'docker-entry.sh', dest: '~/rpicam-docker/'}
    - { src: 'motion_event.sh', dest: '~/rpicam-docker/'}
    - { src: 'schedule.json', dest: '~/rpicam-docker/'}
    - { src: 'uconfig', dest: '~/rpicam-docker/'}

#- name: build docker image
#  make:
#    chdir: /home/pi/rpicam-docker
#    target: build

- name: build docker image
  docker_image:
    path: ~/rpicam-docker
    name: rpi-cam-web
    state: present 
    tag: rpi-cam-web
    debug: yes

- name: create nfs mount
  shell: docker volume create --opt type='nfs4' --opt o=addr=10.10.10.60,rw --opt device=:/Recordings nfscam
- name: Docker Run container
  become: yes
  shell: docker run -d --name=rpi-cam -p=80:80/tcp --mount source=nfscam,destination=/data --device=/dev/vchiq --device=/dev/vcsm rpi-cam-web --restart always
  args:
    chdir: ~/rpicam-docker
