---
- name: Install pyhton
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - python
    - python-pip


# Installing Docker
- name: adding docker group
  become: yes
  group:
    name: docker
    state: present

- name: Add the user pi and docker to the pi group
  user:
    name: "{{ item }}"
    group: docker
  with_items:
    - pi
    - docker
  become: yes

- name: install docker
  apt:
    name: docker-ce=18.06.2~ce~3-0~raspbian
  

- name: Install docker-compose
  pip:
    name: "{{ item }}"
  become: yes
  with_items:
    - docker-py
    - docker-compose~=1.23.0

#- name: Build docker-compose
#  shell: docker-compose build
