---
- name: Install pyhton
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - python
    - python-pip
    - libffi-dev
    - libssl-dev

# Installing Docker
- name: get docker over curl
  become: yes
  shell: curl -sSL https://get.docker.com | sh

- name: adding docker group
  become: yes
  group:
    name: docker
    state: present

- name: Add the user pi and docker to the pi group
  user:
    name: "{{ item }}"
    group: docker
  with_items:
    - pi
    - docker
  become: yes

- name: install pyhton-backports
  become: yes
  apt:
    name: python-backports.ssl-match-hostname
  

- name: Install docker
  pip:
    name: "{{ item }}"
  become: yes
  with_items:
    - docker-py
    - docker-compose

